### PR TITLE
Fix PCDs count in scenarios table

### LINKED ISSUE #164: [Bug]: Scenarios table shows wrong number of PCDs
### What happened?

For instance, at present scenario 8 shows 3 pcds:

Image

but when opened, there is only one 

Image

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by bgm-databeacon**
# PR Description

The column PCDs count all the data in pcd object and this object now include info about flights that were safe (>9 <15).

## How to try it

Upload a scenario that have PCDs between 15 and 10 NM to check if this PCDs are not counted in the column.

Checklist:

- [x] 🧐 it **works on my machine** (c)
- [x] 📋 added clear **instructions** to try it by a reviewer

## 📕 Changes made

- Filter the PCDs that are safe to not count it.

## Checklist

- [ ] 📚 kept the **docs** updated
- [x] 📕 described the **changes** in this PR description

## Related issues

resolves #164

### CODE REVIEW

File: components/scenario/scenario-table.tsx [hunk 1]
```diff
@@ -36,7 +37,10 @@ export const columns: ColumnDef<ScenarioType>[] = [
         header: () => <div className="text-right">PCDs</div>,
         cell: ({ row }) => {
             const scenarioData = row.getValue('data') as ScenarioData;
-            return <div className="text-right font-medium">{scenarioData.pcds.length}</div>;
+            const countPcds = scenarioData.pcds.filter(
+                (pcd) => pcd.minDistanceNM <= MONITOR_DISTANCE_THRESHOLD_NM
```
Comment (scristobal) [inline components/scenario/scenario-table.tsx:41]: this line is duplicated of https://github.com/tango5-aero/tango5/blob/1f4a66afc72ce7e104939444a7b1f5a474c2689f/lib/domain/pcd.ts#L21

**Review by scristobal — CHANGES_REQUESTED** [review]
I would avoid at all cost duplicate game logic. 

The reason is that we agree game logic is something very likely to be changed in the future, so it is better if the logic is not repeated. That way we do not have to remember to change something in several places, which is extremely likely to happen.

File: lib/constants.ts [hunk 2]
```diff
@@ -7,3 +7,6 @@ export const GAME_INDICATOR_SIZE = 60;
 export const GAME_INDICATOR_STROKE_WIDTH = 6;
 export const GAME_INDICATOR_TRAIL_STROKE_WIDTH = 2;
 export const GAME_TIMEOUT_MS = 30_000;
+
+export const CONFLICT_DISTANCE_THRESHOLD_NM = 5;
+export const MONITOR_DISTANCE_THRESHOLD_NM = 9;
```
Comment (scristobal) [inline lib/constants.ts:12]: I think this do not need to be constant anymore

**Review by mprietopereira — APPROVED** [review]
LGTM!

**Review by scristobal — APPROVED** [review]
👍🏻
