### PR TITLE
155 - Fix redirect when login to init page

### LINKED ISSUE #155: [Bug]: Landing redirects again to landing instead to `/init` when login.
### What happened?

When you login into https://tango5.aero. The login action redirects to landing page again. Only if you press `login` again, the correct redirection is made. 

https://github.com/user-attachments/assets/453d2ed3-c01e-4c7e-b881-4b95c7487365

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by bgm-databeacon**
# PR Description

Fix the redirect when login. Instead / redirect to /init.

## How to try it

1. Login and check if it redirect to /init

Checklist:

- [x] 🧐 it **works on my machine** (c)
- [x] 📋 added clear **instructions** to try it by a reviewer

## 📕 Changes made

Force redirect to /init

## Checklist

- [ ] 📚 kept the **docs** updated
- [x] 📕 described the **changes** in this PR description

## Related issues

resolves #155

### CODE REVIEW

File: app/login/page.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ export default async function Page() {
             <main className="relative z-20 flex h-screen flex-col items-center justify-center gap-6 p-6 md:p-10">
                 <WelcomeTango5Title />
                 <SignedOut>
-                    <SignIn routing="hash" forceRedirectUrl="" />
+                    <SignIn routing="hash" forceRedirectUrl={'/init'} />
```
Comment (mprietopereira) [inline app/login/page.tsx:21]: We could actually merge the `/` and `/init` routes as they are pretty similar. What do you think? @bgm-databeacon @scristobal

Comment (bgm-databeacon) [reply app/login/page.tsx:21]: I like have the both pages, one for presentation of the project and the login to redirect when we have comercial web.

Comment (bgm-databeacon) [reply app/login/page.tsx:21]: And I think that this question don't enter in the scope of this issue.

Comment (mprietopereira) [reply app/login/page.tsx:21]: Absolutely, the PR is good to go as it is 👍🏼

Comment (scristobal) [reply app/login/page.tsx:21]: We would need to refactor anyway, so I would merge this and carry on.

btw. @mprietopereira you need to resolve in order to allow merge
